### ISSUE TITLE
Would it be possible to create a html file for each object in one JSON file?

### ISSUE THREAD

**Issue by Chrisedmo** [5thWall/mustache-render#28]
Hi guys, Im using your grunt task to generate a bunch of html email signatures. However at the moment, each individual email signature is being rendered into one big html file. Would it be possible to render something like this JSON:

    { "people":
      [
        {
          "Name": "First Parry",
          "Title": "Managing Director",
          "Email": "name@company.com",
          "Direct": "44 1481 123456",
          "Mobile": "44 7911 321123"
        },
        {
          "Name": "Gordon Lastname",
          "Title": "Director",
          "Email": "gordon@company.com",
          "Direct": "44 1481 123654",
          "Mobile": "44 7781 123321"
        },
        …

into multiple HTML files using just one mustache template? I tried using various options using the details outlined in [Readme](https://github.com/5thWall/mustache-render#building-long-file-lists).

But it spat out either a JSON file again or an un-rendered mustache template ?

**Comment by corpulentcoffee** [comment]
Depending on your exact needs, if you need to slice up data, something like this might be adaptable:

    mustache_render: {
      emailSignatures: {
        files: grunt.file.readJSON('people.json').people.map(function(person) {
          return {
            data: person,
            template: 'email-signature.mustache',
            dest: person.Name.replace(/\W+/g, '-').toLowerCase() + '.html',
          };
        }),
      },
    },

**Comment by Chrisedmo** [comment]
@corpulentcoffee You absolute legend - that works perfectly. This is a real future time saver. Thanks!
