### ISSUE TITLE
Mix flat data option with file data option params

### ISSUE THREAD

**Issue by oric01** [5thWall/mustache-render#30]
Hi,

Is there a way to mix params from both flat data option and file data option ?

ie.
```
mustache_render: {
   default : {
     options: {
        data : {
           foo : '<%= foo_value_from_local_grunt %>',
           bar: '<%= bar_value_from_local_grunt %>',
         }
     },
     files: [
     {
        data: 'data.json',
        template: 'conf.mst',
        dest: 'conf.js'
      }
      ]
   }
},
```

So `foo` and `bar` will be known in `conf.mst`when parsing occure.

If `foo`, `bar` already exist in `data.json` they are overwriiten by the flat data values.

**Comment by corpulentcoffee** [comment]
If you need to do some custom data manipulation (e.g. merging or whatever) before you render your output, you can do so as long as when you're done you have a `data` object, e.g.:

```javascript
mustache_render: {
  default: {
    files: [{
      data: require('lodash').merge(  // or some other merging function
        grunt.file.readJSON('data.json'),
        {foo: 5, bar: 6}
      ),
      template: 'conf.mst',
      dest: 'conf.js',
    }],
  },
},
```

**Comment by oric01** [comment]
Ok I see. Thx !

**Comment by corpulentcoffee** [comment]
Sure thing! Hope that helped get you where you needed to be.
