### ISSUE TITLE
How to render Line Breaks from JSON

### ISSUE THREAD

**Issue by Chrisedmo** [5thWall/mustache-render#31]
Hi there - I' have been using this quite a lot to generate masses of email signatures - so thank you. However today I came across a new problem, how could i render line breaks? For example I have and address that is in a single field, but has /n spaces in there and Ideally I would like it to render as follows:

First Line
Second Line
Etc…

Any ideas how to make this work? Thanks.

**Comment by corpulentcoffee** [comment]
How the whitespace (e.g. newlines, more than one consecutive space) depends on what your template is generating.

Let's say you have a `template.html.mustache` like this:

````mustache
<h1>My Address</h1>
<div>{{address}}</div>
````

And a `Gruntfile.js` like this:

````javascript
module.exports = function(grunt) {
  'use strict';

  grunt.task.loadNpmTasks('grunt-mustache-render');
  grunt.config.init({
    mustache_render: {
      pages: {
        data: {address: "199 W. 39th St.\nBaltimore, MD  21211\nUS"},
        template: 'template.html.mustache',
        dest: 'output.html',
      },
    },
  });
};
````

That generates an `output.html` like this:

````html
<h1>My Address</h1>
<div>199 W. 39th St.
Baltimore, MD  21211
US</div>
````

This will yield the address all one line.

For HTML, here are some ideas:

1. use a `<pre>` tag in your `template.html.mustache`, e.g.:

   ```mustache
   <h1>My Address</h1>
   <pre>{{address}}</pre>
   ```

2. use CSS in your `template.html.mustache` to make your block either behave like a `<pre>` or at least preserve line breaks, e.g.:

   ```mustache
   <h1>My Address</h1>
   <div style="white-space: pre">{{address}}</div>
   ```

   ```mustache
   <h1>My Address</h1>
   <div style="white-space: pre-line">{{address}}</div>
   ```

3. leave your template as it is but use a custom `escape` function, e.g.:

   ```javascript
   grunt.task.loadNpmTasks('grunt-mustache-render');
   grunt.config.init({
     mustache_render: {
       pages: {
         data: {address: "199 W. 39th St.\nBaltimore, MD  21211\nUS"},
         template: 'template.html.mustache',
         dest: 'output.html',
         options: {
           escape: function(input) {
             return require('mustache').
                    escape(input).
                    replace(/\n/g, '<br>').
                    replace(/ /g, '&nbsp;');
           },
         },
       },
     },
   });
   ```

Hope that helps!

**Comment by Chrisedmo** [comment]
Thanks - that's a great help - we managed to actually render the HTML correctly by using the {{{ }}} tags as the JSON data we had, had the correct breaks in.

These are good to know - especially the third option.
