### ISSUE TITLE
Outputting in folder structure plus wrong extention

### ISSUE THREAD

**Issue by simplyynot** [5thWall/mustache-render#33]
My grunt build is setup like this and when processed it builds out into build/crd/(file_name).json.
This only occurs when you use src:*.json to process all the json files with one template. Is there something wrong with my setup or is this a bug?
mustache_render: {
			temp: {
				files: [{
					expand: true,
					src: 'crd/*.json',
					template: 'src/template/core.pheripherials.mustache',
					dest: 'build'
				}]
			}
		}

**Comment by corpulentcoffee** [comment]
The example you pasted doesn't have any wildcards, so I would expect it "expand" to a single source/destination (i.e. `build/crd/.json` would be generated after injecting the data from `crd/.json` into `src/template/core.pheripherials.mustache`).

Did you mean `src: 'crd/*.json'`?

**Comment by simplyynot** [comment]
Yes i did, I'm not sure why that part didn't copy and paste correctly but i have it as src: 'crd/*.json'

**Comment by corpulentcoffee** [comment]
With the wildcard there, every `xxx.json` file in your `crd` subdirectory should be injected into the `src/template/core.pheripherials.mustache` template, and then output as `build/crd/xxx.json`.

Is this what you want/expect, or are you wanting/expecting something else?

**Comment by simplyynot** [comment]
I was expecting it to build out to build/*.html instead of .json, currently I'm using copy to rename this to .html and clean to delete the excess build/crd folder. Is there a more efficient way to just use mustache_render?

**Comment by corpulentcoffee** [comment]
For that, try adding `ext: '.html'` to your expansion, e.g.:

    files: [{
      expand: true,
      src: 'crd/*.json',
      template: 'src/template/core.pheripherials.mustache',
      dest: 'build',
      ext: '.html',
    }]

If you want your HTML files at the root of the build directory, you may also want `flatten: true`, e.g.:

    files: [{
      expand: true,
      src: 'crd/*.json',
      template: 'src/template/core.pheripherials.mustache',
      dest: 'build',
      ext: '.html',
      flatten: true,
    }]

**Comment by simplyynot** [comment]
Oh that worked like a charm. Thank you! I'm still very new to grunt so a big learning process but having fun with this module.

**Comment by corpulentcoffee** [comment]
You're welcome. Good luck with your work!
