### ISSUE TITLE
Partials with explicit scope don't work

### ISSUE THREAD

**Issue by ertyseidohl** [5thWall/mustache-render#34]
Expected:

```{{> mypartial hello}}```

should render the partial ```mypartial``` using ```hello``` as the scope.

Actual:

Error: ```>> Warning: partial reference mypartial hello yields templates/mypartial hello.mustache, which does not exist```

**Comment by 5thWall** [comment]
I'm sorry. I don't seem to see anything about partial scope in the [mustache documentation](https://mustache.github.io). Perhaps you're thinking of [Handlebars.js templates](http://handlebarsjs.com/partials.html)?

**Comment by ertyseidohl** [comment]
@5thWall haha whoops! First time using just mustache without handlebars :+1:
