### ISSUE TITLE
Code output indentation

### ISSUE THREAD

**Issue by marek95** [5thWall/mustache-render#35]
Hi,
is there any way to control indentation of html output? for example when i include a partial it doesnt start outputing code where exactly where i call it but on the begining of that line. If I define multiline variable in data file lines start on the beggining of the line (expect the first line)

data YAML file
```yaml
variable: |
    <main>
    <main>
```

template
```mustache
<body>
  <div>
    {{> partial }}
    {{{ variable }}}
  </div>
</body>
```

partial file
```mustache
<p>text...</p>
```

HTML output
```html
<body>
  <div>
<p>text...</p>
    <main>
<main>

  </div>
</body>
```

Desired HTML output
```html
<body>
  <div>
    <p>text...</p>
    <main>
    <main>
  </div>
</body>
```
is there any way to do it?

**Comment by 5thWall** [comment]
I'm sorry, I've checked the mustache documentation and documentation for the mustache library that we're using and I haven't found anything related to output indentation. Unfortunately this wouldn't be something we could add unless the mustache renderer implements it.
