### ISSUE TITLE
Common data in multiple files

### ISSUE THREAD

**Issue by marek95** [5thWall/mustache-render#36]
Hi,

I am using something like this in my gruntfile.js, so i can compile multiple templates using common data file.

```js
files: [
  {expand: true,
   src: 'template/to/read-*.mustache',
   data: 'common-data.json',
   dest: 'dest/directory/'}
]
```
however, as my common-data.json file grows, it would be nice to have it divided into separate files. 

is it possible to do it somehow?

thanks!

**Comment by 5thWall** [comment]
I'm sorry no, it's not possible to do that at this time. You could get around this by reading in your separate data files and compiling them into a single object and passing that as your data parameter.

**Comment by marek95** [comment]
thanks, thats a good idea, i will look into that

**Comment by marek95** [comment]
so i have it working. in case someone has the same problem, grunt-contrib-concat works well to concatenate data files (I use YAML format)
