### ISSUE TITLE
Dynamic filesets replicating source path

### ISSUE THREAD

**Issue by willharrell** [5thWall/mustache-render#37]
Instances where I utilize a single json and render all temolates in a dir, the full source path is being replicated under my dest location.  For example.  If my src is "foo/bar/*.HTML" and dest is "dest/" the result will be 

dest/foo/bar/[filename].html

**Comment by corpulentcoffee** [comment]
Do you want to share your Gruntfile configuration?

**Comment by willharrell** [comment]
I started with,

"test_task": {
	options: {
		'directory': 'project/project-template/tpl'
		, 'clear_cache': true
		, "extension": '.html'
	}
	, files: [
		{
			expand: true
			, data: 'project/project-template/mdl/things.json'
			, src: 'project/project-template/tpl/*.html'
			, dest: 'project/project-template/dist/'
		}
	]			
}

I was able to resolve the issue by rewriting the dest path through the 'rename' option,

"test_task": {
	options: {
		'directory': 'project/project-template/tpl/'
		, 'clear_cache': true
		, "extension": '.html'
	}
	, files: [
		{
			expand: true
			, data: 'project/project-template/mdl/main.json'
			, src: 'project/project-template/tpl/*.html'
			, dest: ''
			, rename: function(_dest, _src){
				return _src.replace('/tpl/', '/dist/');
			}
		}
	]			
}

However this only works for one project.  I'll have many projects under /project/.  I'd like to write a more dynamic path set than with cover all the projects under /project/ and accomplish the same task as above per project.  Any ideas on how I could do this?  Only way I see is to write a script that will build the paths for each project and return an array of 'files':{}.  Thanks for the assistance!
