### ISSUE TITLE
Update NPM Module

### ISSUE THREAD

**Issue by jvilk** [5thWall/mustache-render#39]
Could you update your NPM module to pull in your `peerDependencies` change? Currently, users of `grunt v1.0` receive the following warning:

```
npm WARN grunt-mustache-render@1.9.0 requires a peer of grunt@^0.4.5 but none was installed.
```

I would greatly appreciate it.

Thanks!

**Comment by 5thWall** [comment]
Weirdly, when I tried publishing to NPM it said that I couldn't overwrite v1.9.1, even though the latest version was set at v1.9.0. I've bumped to v1.9.2 and that seems to have taken.

**Comment by jvilk** [comment]
Thanks! `npm outdated` gave me a weird message about how my `package.json` "wanted `1.9.1` but had `1.9.0` installed", but I could not induce NPM to install the mythical `1.9.1` nor find evidence of it on NPM's site. Sounds like a bug.
